### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Yuri-Ananyev** [Yuri-Ananyev/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by hiphap** [comment]
<h3>Ryu Hoshi</h3>
<ul>
<li><a href="https://www.facebook.com/profile.php?id=100004808958030" rel="nofollow">https://www.facebook.com/profile.php?id=100004808958030</a></li>
<li><a href="mailto:ryuwins@gmail.com">ryuwins@gmail.com</a></li>
<li><a href="https://twitter.com/denjinryu" rel="nofollow">https://twitter.com/denjinryu</a></li>
<li><a href="https://www.instagram.com/sworn_ryu/" rel="nofollow">https://www.instagram.com/sworn_ryu/</a></li>
</ul>
