### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Yuri-Ananyev** [Yuri-Ananyev/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by hiphap** [comment]
<h4>LIFE &amp; EDUCATION</h4>
<p>To live is to fight and to fight is to live.
I  started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.</p>
<h4>LANGUAGES</h4>
<p><g-emoji class="g-emoji" alias="us" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1fa-1f1f8.png">🇺🇸</g-emoji> ENGLISH <g-emoji class="g-emoji" alias="cn" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1e8-1f1f3.png">🇨🇳</g-emoji> MANDARIN <g-emoji class="g-emoji" alias="jp" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1ef-1f1f5.png">🇯🇵</g-emoji> JAPANESE</p>
<h4>SKILLS</h4>
<p>KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS</p>
<h4>CHARACTER</h4>
<p>NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
<h4>LIFE LESSON</h4>
<p>You must defeat Sheng Long to stand a chance.</p>
<h4>LIKES <g-emoji class="g-emoji" alias="smiley" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f603.png">😃</g-emoji></h4>
<p>GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY</p>
<h4>DISLIKES <g-emoji class="g-emoji" alias="disappointed" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f61e.png">😞</g-emoji></h4>
<p>BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
<h4>WANTS ó_ò</h4>
<p>BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</p>
